x = "I am learning pythoN"
mydict = {80: 83}
print(x)
print(type(x))
print(x.upper())
print(x.lower())
print(x.capitalize())
print(x.title())
print(x.swapcase())
print(x.center(50))
print(x.center(50,'^'))
print(x.center(50,'v'))
print(x.replace('pythoN','PHP'))
print(x.find('am'))
print(x.find('Am'))
print(x.count('A'))
print(x.count('a'))
print(x.count('N'))
print(x.startswith('I'))
print(x.startswith('i'))
print(x.endswith('n'))
print(x.endswith('N'))
print(x.translate('am'))
print(x.translate(mydict))
print(x.split())

word = x.split()
print(word)
print(word[3])
print(word[2])

y = 10
print(type(y))
print(dir(y))